#!/usr/bin/env python3
"""Generate slash-command markdown files from `command_specs.py`.

Renders each `CommandSpec` into two output paths:

1. Claude Code plugin tree → `commands/<name>.md`
   - used by `/plugin install agy-web-search` from the marketplace path.
   - frontmatter: `description:` + optional `argument-hint:`.
   - opencode-only fields are NOT emitted (Claude ignores them anyway).

2. opencode global commands → `opencode-commands/<name>.md`
   - used by `agy-route install --target opencode` (file gets dropped at
     `~/.config/opencode/commands/<name>.md`, which opencode auto-loads).
   - frontmatter mirrors Claude Code plus opencode-only optional fields
     (`agent`, `model`, `subtask`).

Both outputs are committed to the repo (with a header comment that
says "auto-generated"), so they ship inside the wheel via force-include
in pyproject.toml.

Run from the repo root:

    python3 tools/generate_commands.py
    python3 tools/generate_commands.py --check
"""
from __future__ import annotations

import sys
from pathlib import Path

# Direct invocation: load command_specs.py as a sibling module.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from command_specs import COMMAND_SPECS, CommandSpec  # type: ignore  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
CLAUDE_OUT = REPO_ROOT / "commands"
OPENCODE_OUT = REPO_ROOT / "opencode-commands"

AUTO_GEN_HEADER = (
    "{auto_marker}\n"
    "<!-- This file is auto-generated by tools/generate_commands.py from\n"
    "     tools/command_specs.py + tools/bodies/<name>.md. Edit those and\n"
    "     re-run the generator instead of editing this file directly. -->\n\n"
)


def _format_claude(spec: CommandSpec) -> str:
    """Render the Claude Code command markdown (frontmatter + body)."""
    lines = []
    lines.append("---")
    lines.append(f"description: {spec.description}")
    if spec.argument_hint:
        lines.append(f'argument-hint: "{spec.argument_hint}"')
    lines.append("---")
    lines.append("")
    lines.append(spec.body.rstrip())
    lines.append("")
    return "\n".join(lines)


def _format_opencode(spec: CommandSpec) -> str:
    """Render the opencode command markdown (richer frontmatter + body)."""
    lines = []
    lines.append("---")
    lines.append(f"description: {spec.description}")
    if spec.argument_hint:
        lines.append(f'argument-hint: "{spec.argument_hint}"')
    if spec.opencode_agent:
        lines.append(f"agent: {spec.opencode_agent}")
    if spec.opencode_model:
        lines.append(f"model: {spec.opencode_model}")
    if spec.opencode_subtask is not None:
        lines.append(f"subtask: {'true' if spec.opencode_subtask else 'false'}")
    lines.append("---")
    lines.append("")
    lines.append(spec.body.rstrip())
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    check_mode = "--check" in sys.argv
    CLAUDE_OUT.mkdir(exist_ok=True)
    OPENCODE_OUT.mkdir(exist_ok=True)
    out_of_date = False

    for spec in COMMAND_SPECS:
        claude_md = (AUTO_GEN_HEADER.format(auto_marker="") + _format_claude(spec)).lstrip()
        opencode_md = (
            AUTO_GEN_HEADER.format(
                auto_marker="<!-- AUTO-GENERATED; see tools/generate_commands.py. -->\n"
            )
            + _format_opencode(spec)
        ).lstrip()

        claude_path = CLAUDE_OUT / f"{spec.name}.md"
        opencode_path = OPENCODE_OUT / f"{spec.name}.md"

        if check_mode:
            if not claude_path.is_file() or claude_path.read_text() != claude_md:
                print(f"OUT OF DATE: {claude_path}", file=sys.stderr)
                out_of_date = True
            if not opencode_path.is_file() or opencode_path.read_text() != opencode_md:
                print(f"OUT OF DATE: {opencode_path}", file=sys.stderr)
                out_of_date = True
        else:
            claude_path.write_text(claude_md)
            opencode_path.write_text(opencode_md)
            print(f"wrote commands/{spec.name}.md + opencode-commands/{spec.name}.md")

    if check_mode:
        if out_of_date:
            print("Command files are out of date. Run 'python3 tools/generate_commands.py' to update.", file=sys.stderr)
            sys.exit(1)
        else:
            print("All generated commands are up to date.")


if __name__ == "__main__":
    main()
